spring:
  config:
    import: classpath:secret.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${db.name}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${db.dbms.username}
    password: ${db.dbms.password}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: DEBUG
        web: DEBUG
jwt:
  secret-key: ${jwt.secret-key}